[package]
name = "repost_rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = { version = "1.0.79", features = [] }
tracing-subscriber = "0.3.18"
instagram-scraper-rs  = { path = "/Users/john/Desktop/Projects/instagram-scraper-rs" }
teloxide = { version = "0.12", features = ["macros", "throttle"] }
log = "0.4"
pretty_env_logger = "0.4"
rand = "0.8.5"
lazy_static = "1.4.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
chrono = "0.4.34"
indexmap = {version = "2.2.3", features = ["serde"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
regex = "1.10.3"
r2d2 = "0.8.10"
r2d2_sqlite = "0.24.0"
urlencoding = "2.1.3"
serde_yaml = "0.9.32"
futures = "0.3.30"
