#file: noinspection SpellCheckingInspection

# Rename the file to credentials.yaml and fill in the values

repostrusty:
  username: "repostrusty"
  password: "password"
  instagram_business_account_id: "xxxxxxxxxxxxxxxxx"
  fb_access_token: "xxxxxxxxxxxxxxxxx"
  discord_token: "xxxxxxxxxxxxxxxxx"
  s3_access_key: "xxxxxxxxxxxxxxxxx"
  s3_secret_key: "xxxxxxxxxxxxxxxxx"
  db_username: "user"
  db_password: "xxxxxxxxxxxxxxxxx"
  enabled: "true"
